### ISSUE TITLE
Error with read.xlsx when knitting a syndrome eval

### ISSUE THREAD

**Issue by DOH-SRE1303** [sara-chronister/syndrome-definition-evaluation#1]
![image](https://user-images.githubusercontent.com/84819789/183174585-c290a995-9218-4a80-81ef-fe6892e7231c.png)

Had trouble getting this markdown to run as directed in the README. The support code was installing missing packages and loading existing ones properly, but it appears my version of `openxlsx` was not working with this code. I reinstalled the package manually and updated it to `4.2.5` and this seems to allow the code to run.

**Comment by DOH-SNC1303** [comment]
Recently updated package management, should have addressed this issue
