### ISSUE TITLE
Validation Review R-Markdown Report Templates Disappeared

### ISSUE THREAD

**Issue by Tyler-Bonnell** [sara-chronister/syndrome-definition-evaluation#29]
Hi @sara-chronister, @DOH-SNC1303  -- when doing a walkthrough with Gabe Haas and other KDHE colleagues, I noticed that the pre-built Validation Review R Markdown reports had accidentally vanished!

**Background:** In the workflow, these Validation Review R Markdown template reports are copied from `Scripts/SupportCode/Validation_Review` (storage filepath) to each `Output/#Def/Syndrome/Validation_Review` subfolder (one set is copied to each syndrome's validation review). 

**Issue:** I believe the reports had accidentally disappeared from `Scripts/SupportCode/Validation_Review` in the GitHub repository due to the `main` branch's `.gitignore` accidentally excluding these template reports. 

**Fix:** 

1. Adjust `main` branch's `.gitignore` to logic that supports the ideal state --> **Ideally, we want GitHub to ignore all `Validation_Review` content (due to some files containing DataDetails, etc.) **except** for this template code (in `Scripts/SupportCode/Validation_Review`).**

2. Re-Add `Scripts/SupportCode/Validation_Review` code to the GitHub repository. It is available on other repo branches (like `15-add-inter-rater-tools`) [here](https://github.com/sara-chronister/syndrome-definition-evaluation/tree/15-add-inter-rater-tools/SupportCode/Validation_Review).

I'm happy to set up a time to fix this with you --- or work on the fix once I get account access in July!

**Comment by DOH-SNC1303** [comment]
completed
